### PR TITLE
Stage 8 of clang compiler warning patches.

### PR DESCRIPTION
**Pull request by ethoms**
Stage 8: *CAUTION*

I have scrapped my original patches that descretely fix build errors on FreeBSD (or rather libobjc2). SOPE is riddled with messy runtime compatability definitions, dating back a long time. I'm talking about 'sel_eq', 'sel_get_name', 'objc_malloc', 'objc_free' etc. There was lots of ugly, inconsistent and nonsensical #if's and #ifdefs for all the different brands and ages of Objective C runtimes.

So, I cleaned up all this stuff in the common.h header files, and used only the modern calls throughout the implementation code. But of course, I was worried about the compatability with the various platforms and older runtimes. So I installed RHEL 5.11 in VirtualBox and managed to build SOPE from my github fork. It worked like a charm!

So, the GNUstep Runtime (libobjc2) and the GCC Runtime (libobjc) >= 4.1.2 build successfully with all my changes up to Stage 8. But I have not tested on any Apple/NeXT Runtimes (Mac OS X), since I don't have access to OS X. According to David Chisnall, it should be OK to use the same modern calls that work in libobjc2.

If the support needs to go back further, and the modern calls are not OK. Then I can add back some much neater, consolidated compatability definitions. I suggest each common.h header file include a project wide header file called runtime_compat.h. Then the runtime specific substitutions could all go in one place.

There is potential for much more, similar, cleanup in SOPE.

### CODE REVIEW

File: sope-core/NGStreams/NGByteCountStream.m [hunk 1]
```diff
@@ -85,10 +85,9 @@ - (unsigned)readBytes:(void *)_buf count:(unsigned)_len {
 
   totalReadCount += result;
   {
-    NSInteger len;
     register unsigned char *byteBuffer = _buf;
 
-    for (len = result - 1; len >= 0; len--, byteBuffer++) {
+    for (NSInteger len = result - 1; len >= 0; len--, byteBuffer++) {
```
Comment (buzzdeee) [inline sope-core/NGStreams/NGByteCountStream.m]: You overwrite the changes here that Ludovic did with 37782867bc35981da0ed8593f9389e9761c3f83a ((fix) c99 fixes). That breaks my build with gcc-4.2.1, libobjc2, on my macppc.

File: sope-core/NGStreams/NGByteCountStream.m [hunk 2]
```diff
@@ -105,10 +104,9 @@ - (unsigned)writeBytes:(const void *)_buf count:(unsigned)_len {
 
   totalWriteCount += result;
   {
-    NSInteger len;
     register unsigned char *byteBuffer = (unsigned char *)_buf;
 
-    for (len = result - 1; len >= 0; len--, byteBuffer++) {
+    for (NSInteger len = result - 1; len >= 0; len--, byteBuffer++) {
```
Comment (buzzdeee) [inline sope-core/NGStreams/NGByteCountStream.m]: Same here as above:
You overwrite the changes here that Ludovic did with 37782867bc35981da0ed8593f9389e9761c3f83a ((fix) c99 fixes). That breaks my build with gcc-4.2.1, libobjc2, on my macppc.

NGByteCountStream.m: In function '-[NGByteCountStream readBytes:count:]':
NGByteCountStream.m:90: error: 'for' loop initial declaration used outside C99 mode
NGByteCountStream.m: In function '-[NGByteCountStream writeBytes:count:]':
NGByteCountStream.m:109: error: 'for' loop initial declaration used outside C99 mode

**Comment by ethoms** [comment]
That worries me! That means I didn't branch properly before I made the Stage 8 pull request. Each Stage should be branched from upstream/master before I commit and make a PR. I'll look into this, I may have to redo Stage pull request.

**Comment by buzzdeee** [comment]
Besides the comment above:
Tested this together with the other stages:
OpenBSD -current
  * amd64, clang-3.5, libobjc2-1.8
  * i386, clang-3.5, libobjc2-1.8
  * macppc, gcc-4.2.1, libobjc2-1.8
No issues so far, besides my comment on the stage8 fix

I should mention, on all test boxes I run against a local postgresql 9.4.4, and against LDAP authentication.

**Comment by ethoms** [comment]
Is there an easy way to change the existing commit/PR, and remove the NGByteCountStream.m changes? Otherwise I'll have to close the PR, re-branch from upstream/master, re-apply my changes and redo the PR.

**Comment by ethoms** [comment]
OK, github allows us to do this in an editor, NICE!

So, I've cleared that mistake. But I wonder how to get those changes back into my local copy.
